spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    data-username: root
    url: jdbc:mysql://localhost:3306/dbboy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true